--- #YAML:1.0
name:                Email-Send
version:             2.191
abstract:            Simply Sending Email
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36_01
distribution_type:   module
requires:     
    Email::Address:                1.80
    Email::Simple:                 1.92
    File::Spec:                    0
    Module::Pluggable:             2.97
    Return::Value:                 1.28
    Scalar::Util:                  1.02
    Symbol:                        0.00
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Casey West <casey@geeknest.com>
